name: Deploy to static branch

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.140.0'
          extended: true

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'

      - name: Install JS dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: npx tailwindcss -i ./static/css/input.css -o ./static/dist/output.css --minify

      - name: Build Site
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: production
